# Generated by Django 6.0.2 on 2026-02-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الاحتيال')),
                ('description', models.TextField(verbose_name='وصف مختصر')),
                ('details', models.TextField(default='', verbose_name='التفاصيل الكاملة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
