# Generated by Django 6.0.2 on 2026-02-17 08:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scamtype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='scamtype',
            name='details',
        ),
        migrations.RemoveField(
            model_name='scamtype',
            name='title',
        ),
        migrations.AddField(
            model_name='scamtype',
            name='description_ar',
            field=models.TextField(default='', verbose_name='وصف مختصر (عربي)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scamtype',
            name='description_en',
            field=models.TextField(default='', verbose_name='Short Description (English)'),
        ),
        migrations.AddField(
            model_name='scamtype',
            name='details_ar',
            field=ckeditor.fields.RichTextField(default='', verbose_name='التفاصيل (عربي)'),
        ),
        migrations.AddField(
            model_name='scamtype',
            name='details_en',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Details (English)'),
        ),
        migrations.AddField(
            model_name='scamtype',
            name='title_ar',
            field=models.CharField(default='', max_length=200, verbose_name='العنوان (عربي)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scamtype',
            name='title_en',
            field=models.CharField(default='', max_length=200, verbose_name='Title (English)'),
        ),
    ]
