# Generated by Django 6.0.2 on 2026-02-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_scamtype_description_remove_scamtype_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200, verbose_name='عنوان الرسالة (عربي)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('image', models.ImageField(upload_to='phishing_scenarios/', verbose_name='صورة الرسالة')),
                ('is_scam', models.BooleanField(default=True, verbose_name='هل هي احتيال؟ (نعم = صح)')),
                ('explanation_ar', models.TextField(verbose_name='التفسير بالعربي')),
                ('explanation_en', models.TextField(verbose_name='Explanation in English')),
            ],
        ),
    ]
